### ISSUE TITLE
Error Installing Pods

### ISSUE THREAD

**Issue by MuhammadAhmed1994** [smaidah/RN-BoilerPlateX#1]
The boilerplate is breaking on the pod install step. I am getting the following error

error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./Folio3BoilerPlate1/ios && pod install".
CocoaPods documentation: https://cocoapods.org/
ahmed@ahmed-mb Desktop % cd Folio3BoilerPlate1 
ahmed@ahmed-mb Folio3BoilerPlate1 % ls
__tests__	android		app.json	assets		babel.config.js	index.js	ios		metro.config.js	node_modules	package.json	src		yarn.lock
ahmed@ahmed-mb Folio3BoilerPlate1 % cd ios 
ahmed@ahmed-mb ios % sudo pod install
Password:
Traceback (most recent call last):
	5: from /Users/ahmed/.rbenv/versions/2.6.3/bin/pod:23:in `<main>'
	4: from /Users/ahmed/.rbenv/versions/2.6.3/bin/pod:23:in `load'
	3: from /Users/ahmed/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.0/bin/pod:55:in `<top (required)>'
	2: from /Users/ahmed/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:48:in `run'
	1: from /Users/ahmed/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cocoapods-1.11.0/lib/cocoapods/command.rb:102:in `ensure_not_root_or_allowed!'
/Users/ahmed/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:439:in `help!': [!] You cannot run CocoaPods as root. (CLAide::Help)

**Comment by smaidah** [comment]
try running `sudo chmod -R 777 yourProjectDirectoryName`

**Comment by MuhammadAhmed1994** [comment]
It Worked thanks 👍
